export { default as IconHamburger } from "../../../public/assets/shared/mobile/icon-hamburger.svg";
export { default as BackgroundPatternSmallCircle } from "../../../public/assets/shared/desktop/bg-pattern-small-circle.svg";
export { default as BackgroundPatternHeroHome } from "../../../public/assets/home/desktop/bg-pattern-hero-home.svg";
export { default as IconRightArrow } from "../../../public/assets/shared/desktop/icon-right-arrow.svg";
export { default as IllustrationPassionate } from "../../../public/assets/home/desktop/illustration-passionate.svg";
export { default as IllustrationResourceful } from "../../../public/assets/home/desktop/illustration-resourceful.svg";
export { default as IllustrationFriendly } from "../../../public/assets/home/desktop/illustration-friendly.svg";
export { default as BackgroundPatternDesignPagesIntroMobile } from "../../../public/assets/shared/mobile/bg-pattern-design-pages-intro-mobile.svg";
export { default as BackgroundPatternThreeCircles } from "../../../public/assets/shared/desktop/bg-pattern-three-circles.svg";
